#!/bin/bash
spamboxpidfile=/opt/spambox/pid
logfile=~spambox_watchdog.log

function checkpid
{
if [ -f $spamboxpidfile ]
then
    /sbin/service spambox status |grep "is running"
    if [ $? != 0 ]
    then
        sleep 10
        /sbin/service spambox status |grep "is running"
        if [ $? != 0 ]
	then
	    LOGDATE=`date "+%m-%d-%y [%k:%M:%S]"`
	    /sbin/service spambox start
	    echo "$LOGDATE - started died spambox" >> $logfile
	fi
    fi
fi
}

COUNTER=1
while [ $COUNTER == 1 ]; do

checkpid
sleep 60

done