#line 1 "sub main::stateReset"
package main; sub stateReset {
    my $fh=shift;
    my $this=$Con{$fh};
    my $friend;
    $friend = $Con{$this->{friend}} if (exists $Con{$this->{friend}});
    
    $this->{resetState}++;

    if ($enableCrashAnalyzer && !$this->{relayok} && $this->{lastcmd} =~ /mail from/io && exists $this->{msgtime}) {
        my ($crmf) = $this->{crashbuf} =~ /([^\r\n]+\r\n)$/os;
        my ($crhl) = $this->{crashbuf} =~ /\n((?:ehlo|helo)[^\r\n]+\r\n)/ois;
        removeCrashFile($fh) and
        newCrashFile($fh) and
        ($this->{crashbuf} .= $crhl) and
        ($this->{crashbuf} .= $crmf);
    }

    MaillogClose($fh) if ($this->{maillogfh} || $this->{maillogfilename});
    $this->{maillogbuf} = ''; # attention - allocmem
    delete $this->{mailloglength};
    delete $this->{maillogfilename};
    delete $this->{maillogfh};
    delete $this->{deleteMailLog};
    delete $this->{maillog};
    delete $this->{maillogparm};

    $this->{acceptall} &= 1;    # remove the cip acceptall
    $this->{addMSGIDsigDone} = '';
    $this->{addressedToPenaltyTrap} = '';
    $this->{addressedToSpamBucket} = '';
    $this->{accBackISPIP} = '';
    $this->{alllog} = '';
    $this->{attachcomment} = '';
    $this->{attachdone} = '';
    $this->{averror} = '';
    $this->{backsctrdone} = '';
    $this->{BATVfrom} = '';
    $this->{BATVrcpt} = '';
    $this->{baysprob} = '';
    $this->{bayesdone} = '';
    $this->{bayeslowconf} = '';
    $this->{baystestmode} = '';
    $this->{bombdone} = '';
    $this->{bspams} = '';
    $this->{ccnever} = '';
    $this->{cip} = '';
    $this->{ciphelo} = '';
    delete $this->{cleanSMTPBuff};
    
    $this->{clamscandone} = '';
    $this->{contentonly} = '';
    $this->{datastart} = 0;
    $this->{delaydone} = '';
    $this->{delayed} = '';
    $this->{delayqueue} = '';
    $this->{dkimverified} = '';
    delete $this->{dkimresult};
    $this->{dlslre} = '';
    delete $this->{dmarc};
    $this->{DMARCokDone} = '';
    $this->{doneDoDomainIP} = '';
    $this->{donotdelay} = '';
    $this->{doNotTimeout} = '';
    $this->{filescandone} = '';
    $this->{forgedHeloOK} = '';
    $this->{forgedhelodone} = '';
    $this->{formathelodone} = '';
    delete $this->{forwardSpam};
    $this->{from} = '';
    $this->{hasmallogname} = '';
    $this->{header} = '';
    $this->{headerlength} = 0;
    $this->{headerpassed} = '';
    $this->{hmmconf} = '';
    $this->{HMMdone} = '';
    $this->{hmmprob} = '';
    $this->{hmmres} = '';
    $this->{inerror} = '';
    $this->{intemperror} = '';
    $this->{invalidHeloOK} = '';
    $this->{invalidSenderDomain} = '';
    $this->{invalidSRSBounce} = '';
    $this->{invalidhelodone} = '';
    $this->{isbounce} = '';
    $this->{ispip} = '';
    $this->{isDKIM} = '';
    $this->{ismaxsize} = '';
    $this->{lastwritten} = '';
    $this->{localSenderOK} = '';
    $this->{localsenderdone} = '';
    $this->{loggedIpFromTo} = '';
    $this->{logrecord} = '';
    $this->{maximumuniqueuri} = '';
    $this->{maximumuri} = '';
    $this->{maxRealSize} = $this->{maxSize} = $this->{maxRealSizeExternal} = $this->{maxSizeExternal} = undef;
    $this->{msgiddone} = '';
    $this->{msgidsigdone} = '';
    $this->{MSGIDsigRemoved} = '';
    $this->{messagelow} = '';
    $this->{messagereason} = '';
    mlog($fh,"info: message score is set to $this->{prescore}") if $this->{prescore};
    $this->{messagescore} = $this->{prescore};
    $this->{messagescore} ||= 0;
    $this->{messagescoredone} = '';
    $this->{myheader} = $this->{myheaderCon};
    $this->{nobayesian} = '';
    $this->{nocollect} = '';
    $this->{nodamping} = '';
    $this->{nodelay} = '';
    $this->{nodkim} = '';
    $this->{nohelo} = '';
    $this->{noLog} = '';
    $this->{nomlog} = '';
    $this->{nopb} = '';
    $this->{nopbwhite} = '';
    $this->{noprocessing} = '';
    $this->{noscan} = '';
    $this->{notspamtag} = '';
    $this->{obfuscatedip} = '';
    $this->{obfuscateduri} = '';
    $this->{onwhitelistwasrun} = '';
    delete $this->{orgrcpt};
    delete $this->{org_header};
    $this->{pbblack} = '';
    $this->{PBOK} = '';
    $this->{PBExtremeOK} = '';
    $this->{pbwhite} = '';
    $this->{preheaderlength} = 0;
    $this->{prepend} = '';
    $this->{rblcache} = '';
    $this->{rblcachedone} = '';
    $this->{rbldone} = '';
    $this->{rblfail} = '';
    $this->{rblneutral} = '';
    $this->{received} = '';
    delete $this->{received354};
    delete $this->{requiredCMD};
    $this->{rcptnoprocessing} = '';
    $this->{rcpt} = '';
    %{$this->{rcptlist}} = (); undef %{$this->{rcptlist}}; delete $this->{rcptlist};
    $this->{redsl} = '';
    $this->{red} = '';
    $this->{RFC2047} = '';    # non printable in MIME encoded
    $this->{runlvl1PL} = '';
    $this->{rwlok} = 0;
    $this->{saveprepend2} = '';
    $this->{saveprepend} = '';
    $this->{sayMessageOK} = '';
    delete $this->{scanfile};
    $this->{senderok} = '';
    @{$this->{senders}} = (); undef @{$this->{senders}}; delete $this->{senders};
    $this->{signed} = '';
    @{$this->{sip}} = (); undef @{$this->{sip}}; delete $this->{sip}; delete $this->{ssip};
    delete $this->{skipBayes};
    $this->{skipuriblPL} = '';
    $this->{skipnotspam} = '';
    $this->{spambuf} = 0;
    $this->{SpamCollectAddress} = '';
    $this->{spamconf} = 0;
    $this->{spamfound} = '';
    $this->{spamloverdone} = '';
    $this->{spamlover} = 0;
    $this->{spamprob} = 0;
    $this->{spfok} = '';
    delete $this->{spf_result};
    $this->{spfstrict} = '';
    $this->{SRSnewAddress} = '';
    $this->{SRSorgAddress} = '';
    $this->{StatsmsgDelayed} = '';
    $this->{tagmode} = '';
    delete $this->{testmode};
    @{$this->{trapaddr}} = ();
    $this->{validHeloOK} = '';
    $this->{validhelodone} = '';
    $this->{uribldone} = '';
    $this->{uri_listed_by} = '';
    $this->{userTempFail} = '';
    $this->{whitelisted} = '';
    $this->{writtenDataToFriend} = 0;
    $this->{mailfrom} = '';
    delete $this->{qdata};
    delete $friend->{qdata}  if $friend;
    delete $this->{noMoreQueued};
    delete $friend->{noMoreQueued} if $friend;
    $this->{IPinHeloOK} = '';
    $this->{BlackDomainOK} = '';
    %{$this->{NoSpoofingOK}} = (); delete $this->{NoSpoofingOK};
    $this->{RWLokDone} = '';
    $this->{FromStrictOK} = '';
    $this->{SPFokDone} = '';
    $this->{BombHeaderOK} = '';
    $this->{BlackHeloOK} = '';
    $this->{MXAOK} = '';
    $this->{PTROK} = '';
    $this->{ScriptOK} = '';

    $this->{originalsubject} = '';
    $this->{subject} = '';
    $this->{subject2} = '';
    $this->{subject3} = '';
    undef %{$this->{Xheaders}}; delete $this->{Xheaders};

    $this->{allLoveSpam} = 0;
    $this->{allLoveBaysSpam} = 0;
    $this->{allLoveBlSpam} = 0;
    $this->{allLoveBoSpam} = 0;
    $this->{allLoveHiSpam} = 0;
    $this->{allLoveSBSpam} = 0;
    $this->{allLovePBSpam} = 0;
    $this->{allLoveISSpam} = 0;
    $this->{allLovePTRSpam} = 0;
    $this->{allLoveHlSpam} = 0;
    $this->{allLoveSPFSpam} = 0;
    $this->{allLoveRBLSpam} = 0;
    $this->{allLoveSRSSpam} = 0;
    $this->{allLoveDLSpam} = 0;
    $this->{allLoveMXASpam} = 0;
    $this->{allLoveBombsSpam} = 0;
    $this->{allLoveURIBLSpam} = 0;
    $this->{allLoveATSpam} = 0;
    $this->{spamloversonly} = '';

    delete $this->{DKIMadded};
    delete $this->{DKIMpreCheckOK};
    delete $this->{SenderBaseOK};
    delete $this->{TLSqueue};
    delete $this->{TestMessageScore};
    delete $this->{addMyheaderTo};
    delete $this->{bdata};
    delete $this->{blackredone};
    delete $this->{cipdone};
    delete $this->{clean};
    delete $this->{gotAllText};
    delete $this->{gripdone};
    delete $this->{hmmValues};
    delete $this->{hmmdone};
    delete $this->{islocalmailaddress};
    delete $this->{maillength};
    delete $this->{mimehead};
    delete $this->{msgid};
    delete $this->{mycountry};
    delete $this->{noop};
    delete $this->{noreportTo};
    delete $this->{numrcpt};
    delete $this->{overwritedo};
    delete $this->{passingreason};
    delete $this->{rcptNonexistent};
    delete $this->{rcptValidated};
    delete $this->{received_spf};
    delete $this->{rwlstatus};
    delete $this->{skipbytes};
    delete $this->{skipmaillog};
    delete $this->{storecompletemail};
    delete $this->{syncServer};
    delete $this->{uhnoprocessing};

    $this->{spamMaxScore} = undef;
    $this->{spamMaxScoreInfo} = '';
    
    $this->{XCLIENT} = $this->{saveXCLIENT} if exists $this->{saveXCLIENT};
    $this->{XFORWARD} = $this->{saveXFORWARD} if exists $this->{saveXFORWARD};

    delete $this->{reportaddr};
    $this->{SIZE} = 0;
    $this->{mfn} = maillogNewFileName();

    $this->{rcvdTime} = time;
    $this->{msgtime} = '';
    $this->{msgtime} = $uniqueIDPrefix if $uniqeIDLogging && $uniqueIDPrefix;
    my $tstamp = substr( $this->{rcvdTime}, 5, 5 );
    $this->{msgtime} .= sprintf( "%s-%05d", $tstamp, $this->{mfn} ) if $uniqeIDLogging;
    if ($this->{lastcmd} =~ /mail from/io && $this->{firstrcvd} && (++$this->{chainMailInSession} > 0)) {
        my $time=$UseLocalTime ? localtime($this->{rcvdTime}) : gmtime($this->{rcvdTime});
        my $tz=$UseLocalTime ? tzStr() : '+0000';
        $time=~s/... (...) +(\d+) (........) (....)/$2 $1 $4 $3/o;
        $this->{rcvd} = $this->{firstrcvd} . "; $time $tz\r\n";
    }
}
