#line 1 "sub main::unloadMainThreadModules"
package main; sub unloadMainThreadModules {
#    unloadNameSpace 'Mail::SPF';
#    unloadNameSpace 'Mail::SPF::Query';
#    unloadNameSpace 'Mail::SRS';
#    unloadNameSpace 'Email::MIME';
#    unloadNameSpace 'MIME::Types';
#    unloadNameSpace 'Email::Send';
#    unloadNameSpace 'Convert::TNEF';
#    unloadNameSpace 'Mail::DKIM::Verifier';
#    unloadNameSpace 'Mail::DKIM';
#    unloadNameSpace 'Mail::DKIM::Signer';
#    unloadNameSpace 'Authen::SASL';

    unloadSub 'BlockedMailResend';
    unloadSub 'BlockReportFromQ';
    unloadSub 'BlockReportText';
    unloadSub 'BlockReportGetCSS';
    unloadSub 'BlockReportGetImage';
    unloadSub 'BlockReasonsGet';
    unloadSub 'BlockReportHTMLTextWrap';
    unloadSub 'cleanBlackPB';
    unloadSub 'CleanCache';
    unloadSub 'cleanCacheBackDNS';
    unloadSub 'cleanCacheBackDNS2';
    unloadSub 'cleanCacheBATVTag';
    unloadSub 'cleanCacheIPNumTries';
    unloadSub 'cleanCacheLocalFrequency';
    unloadSub 'cleanCacheMXA';
    unloadSub 'cleanCachePersBlack';
    unloadSub 'cleanCachePTR';
    unloadSub 'cleanCacheRBL';
    unloadSub 'cleanCacheRWL';
    unloadSub 'cleanCacheSB';
    unloadSub 'cleanCacheSMTPdomainIP';
    unloadSub 'cleanCacheSPF';
    unloadSub 'cleanCacheSSLfailed';
    unloadSub 'cleanCacheURI';
    unloadSub 'CleanDelayDB';
    unloadSub 'CleanPB';
    unloadSub 'cleanTrapPB';
    unloadSub 'cleanUpCollection';
    unloadSub 'cleanUpFiles';
    unloadSub 'cleanUpMaillog';
    unloadSub 'cleanUpMaxFiles';
    unloadSub 'cleanWhitePB';
    unloadSub 'CleanWhitelist';
    unloadSub 'downloadSPAMBOXVersion';
    unloadSub 'downloadBackDNS';
    unloadSub 'downloadDropList';
    unloadSub 'downloadGrip';
    unloadSub 'downloadHTTP';
    unloadSub 'downloadTLDList';
    unloadSub 'downloadVersionFile';
    unloadSub 'exportExtreme';
    unloadSub 'genCerts';
    unloadSub 'genGlobalPBBlack';
    unloadSub 'genGlobalPBWhite';
    unloadSub 'init';
    unloadSub 'installService';
    unloadSub 'LDAPcrossCheck';
    unloadSub 'POP3Collect';
    unloadSub 'resend_mail';
    unloadSub 'write_rebuild_module';
}
